### ISSUE TITLE
OAuth flow with the OTP

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/OTP-Data-Entry#62]
The permissions are soon to be implemented on the OTP at which point add, edit and delete will not work unless a user is logged in, so we must implement this.

Nazareth Events team have done this already so we could talk to them about it.

also mavis has a repo [here](https://github.com/m4v15/OTP_Oauth/blob/master/app.js)

- [x] remind yourself a bit more about oauth flow
- [x] register the app on the platform (mavis needs to do this), with a redirect URI
- [x] when a user tries to add, edit or delete an event, check if they have a token (in the cookies) 
- [x] If a user is not logged in, redirect them to authorize the app with the OTP
  - [x] include in this redirect the correct query parameters
- [x] at our redirect URI deal with the auth code to get an access token
  - [x] extract the code from the query parameters
  - [x] exchange the code for a token by posting to the correct URL with correct query parameters
  - [x] encrypt and store the token in a cookie

**Comment by m4v15** [comment]
- [ ] register the app on the platform (mavis needs to do this), with a redirect URI
- [ ] when a user tries to add, edit or delete an event, check if they have a token (in the cookies)
- [ ] If a user is not logged in, redirect them to authorize the app with the OTP
  - [ ] include in this redirect the correct query parameters
- [ ] at our redirect URI deal with the auth code to get an access token
  - [ ] extract the code from the query parameters
  - [ ] exchange the code for a token by posting to the correct URL with correct query parameters
  - [ ] encrypt and store the token in a cookie
