### ISSUE TITLE
Initial server set up

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/OTP-Data-Entry#9]
- [x] Set up express server - 1hr (#15)
- [x] Set up handlebars - 2hr (#16)
- [x] Deploy to Heroku - 1hr (#17)
- [x] Set up tests - 2hrs (#18)
